{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1dba8b4c-60b5-4f53-8d3d-7e65d9e6b6c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import json\n",
    "import psycopg2\n",
    "from psycopg2.extras import RealDictCursor\n",
    "from datetime import datetime, timedelta\n",
    "import pandas as pd\n",
    "import time"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d4116850-6e1c-491d-8e8b-2b87b5c41bf7",
   "metadata": {},
   "source": [
    "## EXTRACT - TRANSFORM - LOAD"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "bc098592-2477-4d8d-b2a9-044c292306b4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "======================================================================\n",
      "🌤️  MANUAL WEATHER DATA COLLECTION\n",
      "======================================================================\n",
      "📅 Date: 2026-01-02\n",
      "⏰ Time: 21:23:30\n",
      "======================================================================\n",
      "✅ Connected to database\n",
      "\n",
      "📍 Collecting from 4 cities...\n",
      "\n",
      "[1/4] Warsaw, PL\n",
      "   📥 Fetching... ✅\n",
      "   🔄 Transforming... ✅\n",
      "   💾 Saving... ✅ Saved!\n",
      "      0.56°C, light snow\n",
      "\n",
      "[2/4] Krakow, PL\n",
      "   📥 Fetching... ✅\n",
      "   🔄 Transforming... ✅\n",
      "   💾 Saving... ✅ Saved!\n",
      "      0.79°C, broken clouds\n",
      "\n",
      "[3/4] Wroclaw, PL\n",
      "   📥 Fetching... ✅\n",
      "   🔄 Transforming... ✅\n",
      "   💾 Saving... ✅ Saved!\n",
      "      1.39°C, clear sky\n",
      "\n",
      "[4/4] Gdansk, PL\n",
      "   📥 Fetching... ✅\n",
      "   🔄 Transforming... ✅\n",
      "   💾 Saving... ✅ Saved!\n",
      "      1.21°C, moderate rain\n",
      "\n",
      "======================================================================\n",
      "📊 THIS SESSION SUMMARY\n",
      "======================================================================\n",
      "✅ New records: 4\n",
      "⚠️  Duplicates: 0\n",
      "❌ Failed: 0\n",
      "\n",
      "======================================================================\n",
      "📈 TOTAL PROGRESS\n",
      "======================================================================\n",
      "Total records: 113 / 108 (104.6%)\n",
      "\n",
      "Records per city:\n",
      "  Gdańsk          : 28 records\n",
      "  Krakow          : 28 records\n",
      "  Warsaw          : 28 records\n",
      "  Wrocław         : 29 records\n",
      "\n",
      "Collection period: 19 day(s)\n",
      "First: 2025-12-15\n",
      "Last:  2026-01-02\n",
      "\n",
      "======================================================================\n",
      "Progress: [████████████████████████████████████████████████████] 104.6%\n",
      "\n",
      "🎉 TARGET REACHED! You have 100+ records!\n",
      "======================================================================\n",
      "\n",
      "✅ Collection complete! See you next time.\n",
      "======================================================================\n"
     ]
    }
   ],
   "source": [
    "# CONFIGURATION\n",
    "\n",
    "\n",
    "API_KEY = \"f5d78cc13d1ee7bc357815a64011285a\"\n",
    "\n",
    "CITIES = [\n",
    "    (\"Warsaw\", \"PL\"),\n",
    "    (\"Krakow\", \"PL\"),\n",
    "    (\"Wroclaw\", \"PL\"),\n",
    "    (\"Gdansk\", \"PL\")\n",
    "]\n",
    "\n",
    "DB_CONFIG = {\n",
    "    'dbname': 'weather_db',\n",
    "    'user': 'postgres',\n",
    "    'password': 'password',  \n",
    "    'host': 'localhost',\n",
    "    'port': '5432'\n",
    "}\n",
    "\n",
    "def fetch_weather_data(city, country):\n",
    "    \"\"\"Fetch weather from API\"\"\"\n",
    "    url = \"http://api.openweathermap.org/data/2.5/weather\"\n",
    "    params = {\n",
    "        'q': f'{city},{country}',\n",
    "        'appid': API_KEY,\n",
    "        'units': 'metric',\n",
    "        'lang': 'en'\n",
    "    }\n",
    "    \n",
    "    try:\n",
    "        response = requests.get(url, params=params, timeout=10)\n",
    "        if response.status_code == 200:\n",
    "            return response.json()\n",
    "        return None\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "def transform_weather_data(raw_data):\n",
    "    \"\"\"Transform API data\"\"\"\n",
    "    if not raw_data or raw_data.get('cod') not in [200, \"200\"]:\n",
    "        return None\n",
    "    \n",
    "    try:\n",
    "        return {\n",
    "            'city': raw_data['name'],\n",
    "            'country': raw_data['sys']['country'],\n",
    "            'latitude': raw_data['coord']['lat'],\n",
    "            'longitude': raw_data['coord']['lon'],\n",
    "            'temperature': round(raw_data['main']['temp'], 2),\n",
    "            'feels_like': round(raw_data['main']['feels_like'], 2),\n",
    "            'temp_min': round(raw_data['main']['temp_min'], 2),\n",
    "            'temp_max': round(raw_data['main']['temp_max'], 2),\n",
    "            'pressure': raw_data['main']['pressure'],\n",
    "            'humidity': raw_data['main']['humidity'],\n",
    "            'weather_main': raw_data['weather'][0]['main'],\n",
    "            'weather_description': raw_data['weather'][0]['description'],\n",
    "            'wind_speed': round(raw_data['wind']['speed'], 2),\n",
    "            'wind_direction': raw_data['wind'].get('deg', 0),\n",
    "            'clouds': raw_data['clouds']['all'],\n",
    "            'visibility': raw_data.get('visibility', 10000),\n",
    "            'sunrise': datetime.fromtimestamp(raw_data['sys']['sunrise']),\n",
    "            'sunset': datetime.fromtimestamp(raw_data['sys']['sunset']),\n",
    "            'recorded_at': datetime.fromtimestamp(raw_data['dt'])\n",
    "        }\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "def save_to_database(conn, data):\n",
    "    \"\"\"Save to PostgreSQL\"\"\"\n",
    "    sql = \"\"\"\n",
    "    INSERT INTO weather_data (\n",
    "        city, country, latitude, longitude,\n",
    "        temperature, feels_like, temp_min, temp_max,\n",
    "        pressure, humidity,\n",
    "        weather_main, weather_description,\n",
    "        wind_speed, wind_direction,\n",
    "        clouds, visibility,\n",
    "        sunrise, sunset, recorded_at\n",
    "    ) VALUES (\n",
    "        %(city)s, %(country)s, %(latitude)s, %(longitude)s,\n",
    "        %(temperature)s, %(feels_like)s, %(temp_min)s, %(temp_max)s,\n",
    "        %(pressure)s, %(humidity)s,\n",
    "        %(weather_main)s, %(weather_description)s,\n",
    "        %(wind_speed)s, %(wind_direction)s,\n",
    "        %(clouds)s, %(visibility)s,\n",
    "        %(sunrise)s, %(sunset)s, %(recorded_at)s\n",
    "    )\n",
    "    \"\"\"\n",
    "    \n",
    "    try:\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(sql, data)\n",
    "        conn.commit()\n",
    "        cursor.close()\n",
    "        return 'success'\n",
    "    except psycopg2.IntegrityError:\n",
    "        conn.rollback()\n",
    "        return 'duplicate'\n",
    "    except:\n",
    "        conn.rollback()\n",
    "        return 'error'\n",
    "\n",
    "# MAIN COLLECTION\n",
    "\n",
    "def collect_now():\n",
    "    \"\"\"\n",
    "    Main function - Run this 3 times per day\n",
    "    \"\"\"\n",
    "    print(\"\\n\" + \"=\"*70)\n",
    "    print(\"🌤️  MANUAL WEATHER DATA COLLECTION\")\n",
    "    print(\"=\"*70)\n",
    "    print(f\"📅 Date: {datetime.now().strftime('%Y-%m-%d')}\")\n",
    "    print(f\"⏰ Time: {datetime.now().strftime('%H:%M:%S')}\")\n",
    "    print(\"=\"*70)\n",
    "    \n",
    "    # Connect to database\n",
    "    try:\n",
    "        conn = psycopg2.connect(**DB_CONFIG)\n",
    "        print(\"✅ Connected to database\")\n",
    "    except Exception as e:\n",
    "        print(f\"❌ Database connection failed: {e}\")\n",
    "        return\n",
    "    \n",
    "    # Collect from each city\n",
    "    print(\"\\n📍 Collecting from 4 cities...\")\n",
    "    stats = {'success': 0, 'duplicate': 0, 'failed': 0}\n",
    "    \n",
    "    for i, (city, country) in enumerate(CITIES, 1):\n",
    "        print(f\"\\n[{i}/4] {city}, {country}\")\n",
    "        \n",
    "        # Fetch\n",
    "        print(\"   📥 Fetching...\", end=\" \")\n",
    "        raw_data = fetch_weather_data(city, country)\n",
    "        \n",
    "        if not raw_data:\n",
    "            print(\"❌ Failed\")\n",
    "            stats['failed'] += 1\n",
    "            continue\n",
    "        \n",
    "        print(\"✅\")\n",
    "        \n",
    "        # Transform\n",
    "        print(\"   🔄 Transforming...\", end=\" \")\n",
    "        clean_data = transform_weather_data(raw_data)\n",
    "        \n",
    "        if not clean_data:\n",
    "            print(\"❌ Failed\")\n",
    "            stats['failed'] += 1\n",
    "            continue\n",
    "        \n",
    "        print(\"✅\")\n",
    "        \n",
    "        # Save\n",
    "        print(\"   💾 Saving...\", end=\" \")\n",
    "        result = save_to_database(conn, clean_data)\n",
    "        \n",
    "        if result == 'success':\n",
    "            print(f\"✅ Saved!\")\n",
    "            print(f\"      {clean_data['temperature']}°C, {clean_data['weather_description']}\")\n",
    "            stats['success'] += 1\n",
    "        elif result == 'duplicate':\n",
    "            print(\"⚠️  Duplicate (already collected)\")\n",
    "            stats['duplicate'] += 1\n",
    "        else:\n",
    "            print(\"❌ Failed\")\n",
    "            stats['failed'] += 1\n",
    "        \n",
    "        time.sleep(1)\n",
    "    \n",
    "    conn.close()\n",
    "    \n",
    "    # Summary\n",
    "    print(\"\\n\" + \"=\"*70)\n",
    "    print(\"📊 THIS SESSION SUMMARY\")\n",
    "    print(\"=\"*70)\n",
    "    print(f\"✅ New records: {stats['success']}\")\n",
    "    print(f\"⚠️  Duplicates: {stats['duplicate']}\")\n",
    "    print(f\"❌ Failed: {stats['failed']}\")\n",
    "    \n",
    "    # Total progress\n",
    "    print(\"\\n\" + \"=\"*70)\n",
    "    print(\"📈 TOTAL PROGRESS\")\n",
    "    print(\"=\"*70)\n",
    "    \n",
    "    try:\n",
    "        conn = psycopg2.connect(**DB_CONFIG)\n",
    "        cursor = conn.cursor()\n",
    "        \n",
    "        # Total records\n",
    "        cursor.execute(\"SELECT COUNT(*) FROM weather_data\")\n",
    "        total = cursor.fetchone()[0]\n",
    "        \n",
    "        # Records per city\n",
    "        cursor.execute(\"\"\"\n",
    "            SELECT city, COUNT(*) as count \n",
    "            FROM weather_data \n",
    "            GROUP BY city \n",
    "            ORDER BY city\n",
    "        \"\"\")\n",
    "        city_counts = cursor.fetchall()\n",
    "        \n",
    "        # Date range\n",
    "        cursor.execute(\"\"\"\n",
    "            SELECT \n",
    "                MIN(DATE(recorded_at)) as first_day,\n",
    "                MAX(DATE(recorded_at)) as last_day\n",
    "            FROM weather_data\n",
    "        \"\"\")\n",
    "        first_day, last_day = cursor.fetchone()\n",
    "        \n",
    "        cursor.close()\n",
    "        conn.close()\n",
    "        \n",
    "        # Display progress\n",
    "        target = 108\n",
    "        percentage = (total / target) * 100\n",
    "        \n",
    "        print(f\"Total records: {total} / {target} ({percentage:.1f}%)\")\n",
    "        print(f\"\\nRecords per city:\")\n",
    "        for city, count in city_counts:\n",
    "            print(f\"  {city:15} : {count} records\")\n",
    "        \n",
    "        if first_day and last_day:\n",
    "            days = (last_day - first_day).days + 1\n",
    "            print(f\"\\nCollection period: {days} day(s)\")\n",
    "            print(f\"First: {first_day}\")\n",
    "            print(f\"Last:  {last_day}\")\n",
    "        \n",
    "        # Progress bar\n",
    "        print(\"\\n\" + \"=\"*70)\n",
    "        bar_length = 50\n",
    "        filled = int((total / target) * bar_length)\n",
    "        bar = \"█\" * filled + \"░\" * (bar_length - filled)\n",
    "        print(f\"Progress: [{bar}] {percentage:.1f}%\")\n",
    "        \n",
    "        # Next milestone\n",
    "        remaining = target - total\n",
    "        if remaining > 0:\n",
    "            next_runs = (remaining + 3) // 4  # Ceiling division\n",
    "            print(f\"\\n📅 Need {next_runs} more runs to reach {target} records\")\n",
    "            print(f\"   (About {(next_runs + 2) // 3} more days at 3 runs/day)\")\n",
    "        else:\n",
    "            print(\"\\n🎉 TARGET REACHED! You have 100+ records!\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"Could not check progress: {e}\")\n",
    "    \n",
    "    print(\"=\"*70)\n",
    "    print(\"\\n✅ Collection complete! See you next time.\")\n",
    "    print(\"=\"*70)\n",
    "\n",
    "# REMINDER SYSTEM\n",
    "\n",
    "def show_schedule_reminder():\n",
    "    \"\"\"Show when to run next\"\"\"\n",
    "    now = datetime.now()\n",
    "    \n",
    "    # Collection times\n",
    "    times = [\n",
    "        (\"Morning\", 8, 0),\n",
    "        (\"Afternoon\", 14, 0),\n",
    "        (\"Evening\", 20, 0)\n",
    "    ]\n",
    "    \n",
    "    # Find next collection time\n",
    "    next_collection = None\n",
    "    for name, hour, minute in times:\n",
    "        target = now.replace(hour=hour, minute=minute, second=0, microsecond=0)\n",
    "        if target > now:\n",
    "            next_collection = (name, target)\n",
    "            break\n",
    "    \n",
    "    # If no more today, show tomorrow morning\n",
    "    if not next_collection:\n",
    "        tomorrow = now + timedelta(days=1)\n",
    "        target = tomorrow.replace(hour=8, minute=0, second=0, microsecond=0)\n",
    "        next_collection = (\"Morning\", target)\n",
    "    \n",
    "    name, target = next_collection\n",
    "    time_diff = target - now\n",
    "    hours = int(time_diff.total_seconds() // 3600)\n",
    "    minutes = int((time_diff.total_seconds() % 3600) // 60)\n",
    "\n",
    "# MAIN\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    \"\"\"\n",
    "    Run this script manually 3 times per day:\n",
    "    - Morning (08:00)\n",
    "    - Afternoon (14:00)\n",
    "    - Evening (20:00)\n",
    "    \"\"\"\n",
    "    \n",
    "    # Run collection\n",
    "    collect_now()\n",
    "    \n",
    "    # Show reminder for next run\n",
    "    show_schedule_reminder()\n",
    "    \n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d4c7c361-abac-4a6b-87ac-c9302a841712",
   "metadata": {},
   "source": [
    "## Exporting Data to CSV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "47e60c94-031b-4622-92d1-57118379547c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "\n",
    "conn = psycopg2.connect(**DB_CONFIG)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "cursor.execute(\"SELECT * FROM weather_data ORDER BY recorded_at\")\n",
    "data = cursor.fetchall()\n",
    "\n",
    "with open('weather_data.csv', 'w', newline='', encoding='utf-8') as f:\n",
    "    writer = csv.writer(f)\n",
    "    writer.writerow(['id', 'city', 'country', 'latitude','longitude','temperature',\n",
    "                     'feels_like', 'temp_min', 'temp_max', 'pressure','humidity', \n",
    "                     'weather_main,','weather_description', 'wind_speed', \n",
    "                     'wind_direction', 'clouds', 'visibility','sunrise',\n",
    "                     'sunset,','recorded_at','created_at'])\n",
    "    writer.writerows(data)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
